### PR TITLE
Datepicker + Button Design

### PR DESCRIPTION
**Pull request by shikai06**
datepicker in add student + button design in some table. Thanks. :+1:

### CODE REVIEW

**Comment by lloricode** [comment]
hndi rin lumabas sa akin, nag test muna ako, hndi pa naka merge

**Comment by lloricode** [comment]
hanapin ko issue

**Comment by lloricode** [comment]
sa aking issue pala yan, sige ok na yan, wla sa PR mo ang issue

**Comment by lloricode** [comment]
:+1:

**Comment by shikai06** [comment]
ai okie thanks :+1:

**Pull request merged**
